use mysql;
DELETE FROM USER WHERE USER='viz49';
DELETE FROM DB WHERE USER='viz49';
FLUSH PRIVILEGES;

GRANT ALL ON viz49.* TO 'viz49'@'10.120.5.49' IDENTIFIED BY 'XXXXXX';
GRANT ALL ON viz49.* TO 'viz49'@'localhost' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON viz49.*  TO 'viz49'@'10.120.5.49' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON viz49.*  TO 'viz49'@'localhost' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'viz49'@'10.120.5.49' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'viz49'@'localhost' IDENTIFIED BY 'XXXXXX';
FLUSH PRIVILEGES;