var local_reason={
	"0":"OK",
	"1":"An error occurred!Please contact administrator",
	"2":"Unknown error",
	"3":"Service dose not exist!Please contact administrator",
	"4":"Internal error",
	"7":"Character coding errors",
	"8":"Unauthorized!Please check and try again!",
	"9":"You have no right to operate!",
    "10":"Password length must be more than 6",
    "11":"Password length must be more than 30",
    "12":"Password can't be account or reverse order of account",
    "13":"Password too simple, at least 6 '0-9|a-z|A-Z|Other' characters",
    "14":"Password too simple, at least 5 different characters",
	"1000":"Parameters error",
	"2000":"Data already exists!Please check and try again!",
	"3000":"Data does not exist!Please check and try again!",
	"3502":"Original password wrong, please try again",
	"3503":"The role is dependent by some admins, can't delete it",
	"3504":"The role name is already exists",
	"4000":"Service failure",
	"4001":"User not exist or password error",
	"4002":"Confirm password error ",
	"4003":"Invalid password",
	"4004":"User has been locked",
	"4005":"Do not use the recent 3 password",
	"5000":"Internal error",
	"7001":"Verification code error，Please check and try again",
	"7002":"Business logic error，Please check and try again",
	"7003":"The data are dependent, not allowed to delete",
	"7004":"Verify code expired"
};

var local_tags={
    failToOperate: "Operation failed.Please check and resubmit!",
    successToOperate: "Operation successfully",
    modelCreate: "Add",
    modelModify: "Modify",
    httpFail: "Network connection exception",
    accountFirst: "Input valid account first",
    passwordExpiring:"Password will be expired in {0} day(s).<br/>please click the account on the upper-right corner after login<br/> to enter my center and change password.",
    passwordExpired:"Password expired {0} day(s),please change it.",
    loginFirstTime:"Login first time, please change your password ",
    passwordChanged:"Password has changed，please log in again",
    prompt:"Reminder",
	sureToDelete:"Are you sure to delete?",
    rightSet:"Permission setting",
    userAlreadyExists:"User already exists",
    userNotExists:"User does not exist",
    error:"An error occurred! Please contact administrator",
    modifyPassword:"Modify password",
    statusDelete:"Deleted",
    open:"open",
    close:"close",
    
    rights:{
    	c:"add",
    	r:"Enquire",
    	u:"Modify",
    	d:"Delete"
    },
    
    metaNames:{
    	model:"Tree",
    	user:"User management",
    	role:"Role definition",
    		
    	admin:"Administrator",
    	configItem:"Config item",
    	root:"root",
    	group:"Config group",
    	userList:"User management"
    },
    
    deleteSuccess:"Deleted successfully",
    addSuccess:"Add successfully",
    modifySuccess:"Modified successfully",
    all:"All",
    prompt:"Reminder",
    password_expired:"Password expired，do you want to change password?",
    invalid_password:"Password must be more than 6 and less than 30",
    confirm:"Yes",
    cancel:"Cancel",
    verifyCode_validate:"Verification code must match.",
    verifyCode_error:"Verification code input error",
    account_error:"User name or password input error",
    updateSuccessful:"Update successfully"
};
