var local_reason={
	"0":"成功",
	"1":"系统错误",
	"2":"内部错误",
	"3":"内部错误",
	"4":"内部错误",
	"5":"通行证错误",
	"6":"无效的用户临时key",
	"7":"系统忙",
	"8":"请求处理超时",
	"9":"不支持的功能",
	"10":"无效的用户ip",
	
	"2000":"要添加的数据已存在",
	"2001":"数据不存在",

	"3000":"接口错误",
	"3001":"不支持的功能",
	"3002":"未定义",
	"3003":"请求格式错误",
	"3004":"版本错误",
	
	"3502":"原密码错误，请重新输入",
	"3503":"角色被使用，不可以删除",
	"3504":"角色名称已存在",
	
	"4001":"用户不存在，或密码错误",
	"4002":"确认密码错误",
	"4003":"密码不符合安全红线，需要至少8位“0-9|a-z|A-Z|其他可见字符”中的三种，且不重复字符数至少5个",
	"4004":"用户被锁定，不可以登陆",
    
	"4005":"请勿使用最近3次使用的密码",
	"4006":"密码不能少于8位",
    "4007":"密码不能多于30位",
    "4008":"密码强度不够，不重复字符数至少5个",
    "4009":"密码强度不够，需要至少8位“0-9|a-z|A-Z|其他可见字符”中的三种",
    "4010":"密码不能是账号或账号的反序",
	"4011":"验证码输入错误",
	"4012":"验证码过期，请重新输入",
	
	"4100":"用户无权限",
    
	"5000":"内部业务逻辑错误",
	
	"6000":"请求参数错误",
	
	"7002":"错误的数据类型",
	"7003":"该数据被依赖，不可以删除",
	"7004":"用户未认证",
	"10002":"邮件发送失败",
	"20001":"用户没有被锁定",
	
	"8000":"请先输入BI代码",
	"8001":"请先删除该活动对应的广告位信息",
	
	"9001":"请先删除平台对应的广告位信息",
	"9002":"请先删除产品对应的活动信息",
	"9003":"请先删除媒体对应的广告位信息",
	
	"8801":"活动名称、网站名称、频道、广告位、端口所属 重复，请修改以上属性",
	"8802" :"发布时，推广产品、媒体类型、网站名称、频道、广告位、端口所属、着陆平台、着陆页面描述、投放天数、投放日期不可为空,请修改",
	
	"8901":"网站名称已存在"
};

var local_tags={
    failToOperate: "操作失败",
    successToOperate: "操作成功",
    modelCreate: "创建",
    modelModify: "修改",
    httpFail: "网络链接错误",
    accountFirst: "请先输入正确的账号",
    passwordExpiring:"密码还有{0}天将过期，<br/>请登录后，点击右上角账号，进入个人中心修改密码！",
    passwordExpired:"密码已过期{0}天，请修码后，用新密码登陆",
    loginFirstTime:"首次登陆，请修改密码后，用新密码登陆",
    passwordChanged:"密码已修改，请重新登录",
    prompt:"提醒",
    sureToDelete:"是否确定要删除？",
    sureToReset:"是否确定要重置？",
    sureToPublish:"是否确定要发布？",
    sureToProduce:"是否确定要生成？",
    rightSet:"权限设置",
    userAlreadyExists:"用户已存在",
    userNotExists:"用户不存在",
    error:"错误",
    modifyPassword:"修改密码",
    statusDelete:"已删除",
    open:"开启",
    close:"关闭",
    
    "right.c":"增",
    "right.r":"查",
    "right.u":"改",
    "right.d":"删",
    "right.x":"素材",

    "meta.model": "目录树",
    "meta.user": "账号管理",
    "meta.role": "角色管理",
    	
    "meta.admin": "权限管理",
    "meta.configItem": "配置项",
    "meta.root": "根目录",
    "meta.group": "营销系统",
    "meta.userList": "用户管理",
    "meta.spidKey":"密钥管理",
    "meta.spidAuth":"鉴权管理",
    "meta.mktInfo":"营销活动",
    "meta.adInfo":"广告位信息录入",
    "meta.mktLandInfo":"着陆链接(VMALL)",
    "meta.mktLandHonor":"着陆链接(官网)",
    "meta.monitor":"监控代码",
    "meta.mktProductDic":"推广产品",
    "meta.adExport":"投放点位导出",
    "meta.monitorInfo":"监控代码(BI)",
    "meta.mktMediaDic":"广告媒体",
    "meta.mktUserDic":"常用联系人",
    
    "meta.huaweiReport":"流量报表",
    "meta.mktLandForOther":"着落链接(第三方)",
    
    "meta.mktCTransRep":"转化报表",
    "meta.mktOperLog":"日志查询",
    "meta.generalSituat":"分类图表",
    
    "menu.role":"角色管理",
    "menu.userList":"用户管理",
    "menu.spidKey":"密钥管理",
    "menu.spidAuth":"鉴权管理",
    "menu.mktInfo":"营销活动信息",
    "menu.adInfo":"广告信息",
    
    
    
    deleteSuccess:"删除成功",
    confirmDelete:"请确定是否删除?",
    addSuccess:"添加成功",
    modifySuccess:"修改成功",
    all:"所有",
    prompt:"提醒",
    password_expired:"密码已超期，是否修改密码？",
    invalid_password:"密码必须至少6位，最多30位",
    confirm:"确定",
    cancel:"取消",
    successToRstPwd:"重置密码成功",
    successToUnlock:"手动解锁成功",
    newPasswordIs:"新密码是",
    sureToRstPassword:"确定要重置{0}密码吗？",
    verifyCode_validate:"验证码必须填写一致",
    verifyCode_error:"验证码输入错误",
    account_error:"用户名或密码输入错误",
    deleteConfirmTip:"是否删除该条记录?",
    tips:"提醒",
    resetOrunLock:"重置{0}的密码还是手动解锁？",
    resetPwd:"重置密码",
    unLock:"手动解锁",
    updateSuccessful:"更新成功",
    
    createWeb:"创建网站",
    resetToModify:"请重置后编辑",
    mktInfoAlreadyExists:"该营销活动名称已存在，请输入新的营销活动名称",
    mktDicPlatformAlreadyExists:"该平台名称已存在，请输入新的平台名称",
    mktLandInfoNoPublishForNull:"着陆信息为空，不能发布",
    mktDicMediaAlreadyExists:"该媒体类型已存在，请输入新的媒体名称",
    mktDicWebAlreadyExists:"该网站已存在，请输入新的网站名称",
    mktInfoDeliverTimeError: "投放开始时间大于结束时间，请重新输入",
    mktInfoReserveTimeError: "预约开始时间大于结束时间，请重新输入",
    adInfoAlreadyExists : "该广告位信息已经存在，请重新输入广告位信息，活动名称、网站名称、渠道、广告位、端口所属不能重复",
    delMaterial : "删除素材",
    sureToDelMaterial : "确认要删除素材吗？",
    
};
