use mysql;
DELETE FROM USER WHERE USER='odpdb';
DELETE FROM DB WHERE USER='odpdb';
FLUSH PRIVILEGES;

GRANT ALL ON odpdb.* TO 'odpdb'@'%' IDENTIFIED BY 'XXXXXX';
GRANT ALL ON odpdb.* TO 'odpdb'@'localhost' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON odpdb.*  TO 'odpdb'@'%' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON odpdb.*  TO 'odpdb'@'localhost' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'odpdb'@'%' IDENTIFIED BY 'XXXXXX';
quit