use mysql;
DELETE FROM USER WHERE USER='tcc2rs45';
DELETE FROM DB WHERE USER='tcc2rs45';
FLUSH PRIVILEGES;

GRANT ALL ON tcc2rs45.* TO 'tcc2rs45'@'10.120.5.45' IDENTIFIED BY 'XXXXXX';
GRANT ALL ON tcc2rs45.* TO 'tcc2rs45'@'localhost' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON tcc2rs45.*  TO 'tcc2rs45'@'10.120.5.45' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON tcc2rs45.*  TO 'tcc2rs45'@'localhost' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'tcc2rs45'@'10.120.5.45' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'tcc2rs45'@'localhost' IDENTIFIED BY 'XXXXXX';
quit