use mysql;
DELETE FROM USER WHERE USER='tcc2rs';
DELETE FROM DB WHERE USER='tcc2rs';
FLUSH PRIVILEGES;

GRANT ALL ON tcc2rs.* TO 'tcc2rs'@'10.120.5.57' IDENTIFIED BY 'XXXXXX';
GRANT ALL ON tcc2rs.* TO 'tcc2rs'@'localhost' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON tcc2rs.*  TO 'tcc2rs'@'10.120.5.57' IDENTIFIED BY 'XXXXXX';
GRANT EXECUTE,ALTER ROUTINE,CREATE ROUTINE ON tcc2rs.*  TO 'tcc2rs'@'localhost' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'tcc2rs'@'10.120.5.57' IDENTIFIED BY 'XXXXXX';
grant select on mysql.proc to 'tcc2rs'@'localhost' IDENTIFIED BY 'XXXXXX';
quit