--create 't_game_affiliation_d', 'indexvalue'
DROP TABLE game.t_game_affiliation_d_hbase;
CREATE EXTERNAL TABLE game.t_game_affiliation_d_hbase
(
    key                         string      COMMENT '主键',
    dtime                       string      COMMENT '时间，粒度到天',
    currency                    string      COMMENT '货币单位，如USD，CNY',
    projectid                   string      COMMENT '项目ID',
    relchannel                  string      COMMENT '推广渠道',
    activityid                  string      COMMENT '营销活动ID',
    partnerid                   string      COMMENT '合作伙伴ID',
    chargechannelid             string      COMMENT '支付渠道',
    chargechannelname           string      COMMENT '支付渠道名称',
    activityname                string      COMMENT '营销活动名称',
    channelname                 string      COMMENT '推广渠道名称',
    partnername                 string      COMMENT '合作伙伴名称',
    affiliatechannelid          string      COMMENT '子渠道id',
    numacqrate_numerator        int         COMMENT '号码获取率分子',
    numacqrate_denominator      int         COMMENT '号码获取率分母',
    tnewuserunsubusercnt        int         COMMENT '新订购会员退订数',
    actunsubnumofnewsubmem      int         COMMENT '新订购会员主动退订数',
    cusunsubnumofnewsubmem      int         COMMENT '新订购会员客服退订数',
    tunsubscribevips            int         COMMENT '非新增会员退订数',
    tuserunsubusercnt           int         COMMENT '非新增会员主动退订数',
    cusunsubnumofnotnewsubmem   int         COMMENT '非新增会员客服代退订数',
    tnewvips                    int         COMMENT '新增会员数',
    tpaysuccess                 int         COMMENT '一键订购订购成功数量',
    sevendaysrematevips         int         COMMENT '7日留存会员数',
    sevendayordervips           int         COMMENT '7日前订购会员总数',
    sevenrenratenumerator       int         COMMENT '7日留存率均值分子',
    sevenrenratedenominator     int         COMMENT '7日留存率均值分母',
    grantcollectvips            int         COMMENT '应收租会员数',
    treceivablevips             int         COMMENT '成功收租会员数',
    tpartnerchannelrevenue      double      COMMENT '合作渠道流水(美元)',
    localtpartnerchannelrevenue double      COMMENT '合作渠道流水(本币)',
    tviprevenue                 double      COMMENT '会员总流水(美元)',
    localtviprevenue            double      COMMENT '会员总流水(本币)',
    tprotectvips                int         COMMENT '合作渠道会员数',
    tfreevips                   int         COMMENT '免费期会员数',
    tgracevips                  int         COMMENT '宽限期会员数',
    tnormalvips                 int         COMMENT '正式期会员数'
)
STORED BY 'org.apache.hadoop.hive.hbase.HBaseStorageHandler'
WITH SERDEPROPERTIES ("hbase.columns.mapping" = "
    :key,
    indexvalue:DTIME,
    indexvalue:CURRENCY,                 
    indexvalue:PROJECTID,                
    indexvalue:RELCHANNEL,               
    indexvalue:ACTIVITYID,               
    indexvalue:PARTNERID,                
    indexvalue:CHARGECHANNELID,          
    indexvalue:CHARGECHANNELNAME,        
    indexvalue:ACTIVITYNAME,             
    indexvalue:CHANNELNAME,              
    indexvalue:PARTNERNAME,              
    indexvalue:AFFILIATECHANNELID,       
    indexvalue:NUMACQRATE_NUMERATOR,     
    indexvalue:NUMACQRATE_DENOMINATOR,   
    indexvalue:TNEWUSERUNSUBUSERCNT,     
    indexvalue:ACTUNSUBNUMOFNEWSUBMEM,   
    indexvalue:CUSUNSUBNUMOFNEWSUBMEM,   
    indexvalue:TUNSUBSCRIBEVIPS,         
    indexvalue:TUSERUNSUBUSERCNT,        
    indexvalue:CUSUNSUBNUMOFNOTNEWSUBMEM,
    indexvalue:TNEWVIPS,                 
    indexvalue:TPAYSUCCESS,              
    indexvalue:SEVENDAYSREMATEVIPS,      
    indexvalue:SEVENDAYORDERVIPS,        
    indexvalue:SEVENRENRATENUMERATOR,  
    indexvalue:SEVENRENRATEDENOMINATOR,  
    indexvalue:GRANTCOLLECTVIPS,         
    indexvalue:TRECEIVABLEVIPS,          
    indexvalue:TPARTNERCHANNELREVENUE,   
    indexvalue:LOCALTPARTNERCHANNELREVENUE,   
    indexvalue:TVIPREVENUE,              
    indexvalue:LOCALTVIPREVENUE,              
    indexvalue:TPROTECTVIPS,             
    indexvalue:TFREEVIPS,                
    indexvalue:TGRACEVIPS,               
    indexvalue:TNORMALVIPS                        
")   
TBLPROPERTIES ("hbase.table.name" = "t_game_affiliation_d");
GRANT SELECT ON game.t_game_affiliation_d_hbase to user tianjunjie;
GRANT SELECT ON game.t_game_affiliation_d_hbase to user mapred;